version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEMO_APP_ADDR=:8080
      - DEMO_REDIS_ADDR=redis:6379
    depends_on:
      - redis
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:

      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

